# Generated by Django 2.2 on 2019-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relationship_to_head_of_family',
            field=models.CharField(choices=[('head', 'head'), ('father', 'father'), ('mother', 'mother'), ('daughter', 'daughter'), ('child', 'child'), ('brother', 'brother'), ('sister', 'sister'), ('grandfather', 'grandfather'), ('uncle', 'uncle'), ('aunt', 'aunt'), ('father in law', 'father in law'), ('mother in law', 'mother in law'), ('son in law', 'son in law'), ('daughter in law', 'daughter in law'), ('brother in law', 'sister in law'), ('husband', 'husband'), ('wife', 'wife')], default='head', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], max_length=255),
        ),
    ]
